/**
 * @file config.h
 * @brief Configuration definitions and platform detection for EthervoxAI
 *
 * Copyright (c) 2024-2025 EthervoxAI Team
 *
 * This file is part of EthervoxAI, licensed under CC BY-NC-SA 4.0.
 * You are free to share and adapt this work under the following terms:
 * - Attribution: Credit the original authors
 * - NonCommercial: Not for commercial use
 * - ShareAlike: Distribute under same license
 *
 * For full license terms, see: https://creativecommons.org/licenses/by-nc-sa/4.0/
 * SPDX-License-Identifier: CC-BY-NC-SA-4.0
 */

#ifndef ETHERVOX_CONFIG_H
#define ETHERVOX_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// Platform detection macros
#if defined(TARGET_ESP32)
#define ETHERVOX_PLATFORM_ESP32 1
#define ETHERVOX_PLATFORM_EMBEDDED 1
#elif defined(TARGET_RPI)
#define ETHERVOX_PLATFORM_RPI 1
#define ETHERVOX_PLATFORM_EMBEDDED 1
#elif defined(TARGET_WINDOWS)
#define ETHERVOX_PLATFORM_WINDOWS 1
#define ETHERVOX_PLATFORM_DESKTOP 1
#elif defined(TARGET_LINUX)
#define ETHERVOX_PLATFORM_LINUX 1
#define ETHERVOX_PLATFORM_DESKTOP 1
#elif defined(TARGET_MACOS)
#define ETHERVOX_PLATFORM_MACOS 1
#define ETHERVOX_PLATFORM_DESKTOP 1
#endif

// Feature configuration
#define ETHERVOX_LANG_CODE_LEN 8
#define ETHERVOX_PLATFORM_NAME_LEN 32
#define ETHERVOX_PLATFORM_HW_REV_LEN 16
#define ETHERVOX_PLATFORM_CPU_MODEL_LEN 64
#define ETHERVOX_PLATFORM_ERROR_LEN 256
#define ETHERVOX_PLATFORM_ID_LEN 32
#define ETHERVOX_PLATFORM_DEFAULT_TEMP_C 45.0f
#define ETHERVOX_PLATFORM_MIC_COUNT 8
#define ETHERVOX_PLATFORM_MIC_SELECT_PINS 3
#define ETHERVOX_PLATFORM_US_PER_SEC 1000000ULL
#define ETHERVOX_PLATFORM_US_PER_MS 1000ULL

#ifndef ETHERVOX_MAX_LANGUAGES
#ifdef ETHERVOX_PLATFORM_EMBEDDED
#define ETHERVOX_MAX_LANGUAGES 3
#else
#define ETHERVOX_MAX_LANGUAGES 15
#endif
#endif

#ifndef ETHERVOX_AUDIO_SAMPLE_RATE
#define ETHERVOX_AUDIO_SAMPLE_RATE 16000
#endif

#ifndef ETHERVOX_AUDIO_CHANNELS_DEFAULT
#define ETHERVOX_AUDIO_CHANNELS_DEFAULT 1
#endif

#ifndef ETHERVOX_AUDIO_BITS_PER_SAMPLE
#define ETHERVOX_AUDIO_BITS_PER_SAMPLE 16
#endif

#ifndef ETHERVOX_AUDIO_BUFFER_SIZE
#ifdef ETHERVOX_PLATFORM_EMBEDDED
#define ETHERVOX_AUDIO_BUFFER_SIZE 1024
#else
#define ETHERVOX_AUDIO_BUFFER_SIZE 4096
#endif
#endif

#ifndef ETHERVOX_MAX_PLUGINS
#ifdef ETHERVOX_PLATFORM_EMBEDDED
#define ETHERVOX_MAX_PLUGINS 8
#else
#define ETHERVOX_MAX_PLUGINS 32
#endif
#endif

#ifndef ETHERVOX_LLM_MODEL_NAME
#define ETHERVOX_LLM_MODEL_NAME "ethervox-lite"
#endif

#ifndef ETHERVOX_LLM_MAX_TOKENS_DEFAULT
#define ETHERVOX_LLM_MAX_TOKENS_DEFAULT 512U
#endif

#ifndef ETHERVOX_LLM_CONTEXT_LENGTH_DEFAULT
#define ETHERVOX_LLM_CONTEXT_LENGTH_DEFAULT 2048U
#endif

#ifndef ETHERVOX_LLM_TEMPERATURE_DEFAULT
#define ETHERVOX_LLM_TEMPERATURE_DEFAULT 0.7f
#endif

#ifndef ETHERVOX_LLM_TOP_P_DEFAULT
#define ETHERVOX_LLM_TOP_P_DEFAULT 0.9f
#endif

#ifndef ETHERVOX_LLM_SEED_DEFAULT
#define ETHERVOX_LLM_SEED_DEFAULT 42U
#endif

#ifndef ETHERVOX_LLM_GPU_LAYERS_DEFAULT
#define ETHERVOX_LLM_GPU_LAYERS_DEFAULT 99U
#endif

#ifdef ETHERVOX_PLATFORM_DESKTOP
#ifndef ETHERVOX_LLM_MAX_TOKENS_DESKTOP
#define ETHERVOX_LLM_MAX_TOKENS_DESKTOP 1024U
#endif
#ifndef ETHERVOX_LLM_CONTEXT_LENGTH_DESKTOP
#define ETHERVOX_LLM_CONTEXT_LENGTH_DESKTOP 4096U
#endif
#ifndef ETHERVOX_LLM_GPU_LAYERS_DESKTOP
#define ETHERVOX_LLM_GPU_LAYERS_DESKTOP 10U
#endif
#else
#ifndef ETHERVOX_LLM_MAX_TOKENS_DESKTOP
#define ETHERVOX_LLM_MAX_TOKENS_DESKTOP ETHERVOX_LLM_MAX_TOKENS_DEFAULT
#endif
#ifndef ETHERVOX_LLM_CONTEXT_LENGTH_DESKTOP
#define ETHERVOX_LLM_CONTEXT_LENGTH_DESKTOP ETHERVOX_LLM_CONTEXT_LENGTH_DEFAULT
#endif
#ifndef ETHERVOX_LLM_GPU_LAYERS_DESKTOP
#define ETHERVOX_LLM_GPU_LAYERS_DESKTOP ETHERVOX_LLM_GPU_LAYERS_DEFAULT
#endif
#endif

// Android-specific LLM configuration (high performance mobile)
#ifdef ETHERVOX_PLATFORM_ANDROID
#ifndef ETHERVOX_LLM_MAX_TOKENS_ANDROID
#define ETHERVOX_LLM_MAX_TOKENS_ANDROID 200  // Longer responses for voice
#endif
#ifndef ETHERVOX_LLM_CONTEXT_LENGTH_ANDROID
#define ETHERVOX_LLM_CONTEXT_LENGTH_ANDROID 2048U  // Balance context vs memory
#endif
#ifndef ETHERVOX_LLM_GPU_LAYERS_ANDROID
#define ETHERVOX_LLM_GPU_LAYERS_ANDROID 99U  // Offload everything to GPU
#endif
#ifndef ETHERVOX_LLM_BATCH_SIZE_ANDROID
#define ETHERVOX_LLM_BATCH_SIZE_ANDROID 512U  // Batch size for generation (reduced for lower latency)
#endif
#ifndef ETHERVOX_LLM_PROMPT_BATCH_SIZE_ANDROID
#define ETHERVOX_LLM_PROMPT_BATCH_SIZE_ANDROID 64U  // Small batches for low latency (voice queries are short)
#endif
#ifndef ETHERVOX_LLM_MAX_RESPONSE_LENGTH_ANDROID
#define ETHERVOX_LLM_MAX_RESPONSE_LENGTH_ANDROID 4096U  // Maximum response buffer
#endif
#endif

// Debug configuration
#ifdef DEBUG_ENABLED
#define ETHERVOX_DEBUG 1
#define ETHERVOX_LOG_LEVEL 0  // Verbose
#else
#define ETHERVOX_DEBUG 0
#define ETHERVOX_LOG_LEVEL 2  // Error only
#endif

// Version information (single source of truth)
#define ETHERVOX_VERSION_MAJOR 0
#define ETHERVOX_VERSION_MINOR 1
#define ETHERVOX_VERSION_PATCH 0
#define ETHERVOX_BUILD_TYPE "Engineering"

// Build version string from components
#define ETHERVOX_STRINGIFY(x) #x
#define ETHERVOX_TOSTRING(x) ETHERVOX_STRINGIFY(x)
#define ETHERVOX_VERSION_STRING \
  ETHERVOX_TOSTRING(ETHERVOX_VERSION_MAJOR) "." \
  ETHERVOX_TOSTRING(ETHERVOX_VERSION_MINOR) "." \
  ETHERVOX_TOSTRING(ETHERVOX_VERSION_PATCH)

#ifdef __cplusplus
}
#endif

#endif  // ETHERVOX_CONFIG_H