/**
 * @file espeak_dict_data.c
 * @brief Embedded espeak dictionary data (auto-included if headers exist)
 * 
 * This file includes generated espeak dictionary headers to make their
 * const arrays available for linking. The headers are generated by
 * tools/train_phonemizer.sh using espeak-ng as a development tool.
 */

#include "espeak_dict.h"

// Include generated dictionary headers if they exist
// These are checked at CMake configure time via ESPEAK_DICT_*_ENABLED macros

#ifdef ESPEAK_DICT_EN_US_ENABLED
#include "data/espeak_dict_en_us.h"
#endif

#ifdef ESPEAK_DICT_EN_GB_RP_ENABLED
#include "data/espeak_dict_en_gb_rp.h"
#endif

#ifdef ESPEAK_DICT_DE_ENABLED
#include "data/espeak_dict_de.h"
#endif

#ifdef ESPEAK_DICT_CMN_ENABLED
#include "data/espeak_dict_cmn.h"
#endif

#ifdef ESPEAK_DICT_ES_419_ENABLED
#include "data/espeak_dict_es_419.h"
#endif
