/**
 * @file espeak_dict.c
 * @brief Embedded espeak dictionary lookup implementation
 * 
 * LICENSING: MIT License (No GPL Contamination)
 * Copyright (c) 2025 EthervoxAI
 * 
 * This code performs binary search on espeak-generated pronunciation data.
 * The data is generated by a GPL tool (espeak-ng) during build, but:
 * - Data itself is factual information (not copyrightable code)
 * - This lookup code is original MIT-licensed implementation
 * - No espeak code is linked or distributed
 */

#include "espeak_dict.h"
#include "ethervox/logging.h"
#include <string.h>
#include <ctype.h>

/**
 * Case-insensitive comparison
 */
static int strcasecmp_portable(const char* s1, const char* s2) {
    while (*s1 && *s2) {
        int c1 = tolower((unsigned char)*s1);
        int c2 = tolower((unsigned char)*s2);
        if (c1 != c2) return c1 - c2;
        s1++;
        s2++;
    }
    return tolower((unsigned char)*s1) - tolower((unsigned char)*s2);
}

/**
 * Binary search in sorted dictionary
 */
int espeak_dict_lookup(
    const espeak_dict_entry_t* entries,
    size_t size,
    const char* word,
    char* ipa_out,
    size_t max_len
) {
    if (!entries || !word || !ipa_out || size == 0 || max_len == 0) {
        ETHERVOX_LOG_DEBUG("[EspeakDict] Lookup failed: invalid parameters (entries=%p, word=%p, ipa_out=%p, size=%zu, max_len=%zu)",
                           (void*)entries, (void*)word, (void*)ipa_out, size, max_len);
        return -1;
    }
    
    ETHERVOX_LOG_DEBUG("[EspeakDict] 🔍 Looking up '%s' in dictionary (size=%zu entries)", word, size);
    
    // Binary search (dictionary must be sorted by word)
    size_t left = 0;
    size_t right = size - 1;
    size_t iterations = 0;
    
    while (left <= right) {
        size_t mid = left + (right - left) / 2;
        iterations++;
        
        if (!entries[mid].word) {
            ETHERVOX_LOG_DEBUG("[EspeakDict] ❌ Hit sentinel/null entry at mid=%zu", mid);
            break;  // Hit sentinel
        }
        
        int cmp = strcasecmp_portable(word, entries[mid].word);
        
        ETHERVOX_LOG_DEBUG("[EspeakDict]   iter=%zu: left=%zu, mid=%zu, right=%zu, entries[mid].word='%s', cmp=%d",
                           iterations, left, mid, right, entries[mid].word, cmp);
        
        if (cmp == 0) {
            // Found!
            strncpy(ipa_out, entries[mid].ipa, max_len - 1);
            ipa_out[max_len - 1] = '\0';
            ETHERVOX_LOG_DEBUG("[EspeakDict] ✅ Found '%s' → '%s' (after %zu iterations)", word, ipa_out, iterations);
            return 0;
        } else if (cmp < 0) {
            if (mid == 0) {
                ETHERVOX_LOG_DEBUG("[EspeakDict] ❌ Search exhausted (mid=0, would underflow)");
                break;  // Prevent underflow
            }
            right = mid - 1;
        } else {
            left = mid + 1;
        }
    }
    
    ETHERVOX_LOG_DEBUG("[EspeakDict] ❌ Not found: '%s' (searched %zu iterations, final left=%zu, right=%zu)",
                       word, iterations, left, right);
    return -1;  // Not found
}
