/**
 * @file espeak_dict.h
 * @brief Embedded espeak-trained pronunciation dictionaries
 * 
 * LICENSING: MIT License (No GPL Contamination)
 * Copyright (c) 2025 EthervoxAI
 * 
 * These dictionaries are generated offline using espeak-ng (GPL, dev tool only)
 * and embedded at compile time. The pronunciation data itself is factual information
 * (not copyrightable code), similar to a phone book. Espeak-ng is NEVER linked or
 * distributed with this software.
 * 
 * Legal Justification:
 * - Espeak-ng is used as a development/build tool only (like GCC compiling GPL code)
 * - Generated data is factual (word→IPA mappings) not creative/copyrightable
 * - No espeak code is included, only the lookup results
 * - Analogous to using a GPL compiler to build MIT-licensed software
 * 
 * Priority hierarchy:
 * 1. User overrides (pronunciation_overrides.h)
 * 2. Embedded espeak dictionaries (this file)
 * 3. CMU/language-specific dictionaries
 * 4. G2P fallback rules
 */

#ifndef ETHERVOX_ESPEAK_DICT_H
#define ETHERVOX_ESPEAK_DICT_H

#include "ethervox/error.h"
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Dictionary entry: word → IPA pronunciation
 */
typedef struct {
    const char* word;
    const char* ipa;
} espeak_dict_entry_t;

/**
 * Language-specific embedded dictionaries
 * Generated by tools/generate_espeak_dict.py
 */

// English (US) - generated from espeak-ng en-us
#ifdef ESPEAK_DICT_EN_US_ENABLED
extern const espeak_dict_entry_t espeak_dict_en_us[];
extern const size_t espeak_dict_en_us_size;
#endif

// English (GB-RP) - generated from espeak-ng en-gb-x-rp
#ifdef ESPEAK_DICT_EN_GB_RP_ENABLED
extern const espeak_dict_entry_t espeak_dict_en_gb_rp[];
extern const size_t espeak_dict_en_gb_rp_size;
#endif

// German - generated from espeak-ng de
#ifdef ESPEAK_DICT_DE_ENABLED
extern const espeak_dict_entry_t espeak_dict_de[];
extern const size_t espeak_dict_de_size;
#endif

/**
 * Lookup word in embedded espeak dictionary
 * 
 * @param entries Dictionary array (e.g., espeak_dict_en_us)
 * @param size Dictionary size
 * @param word Word to lookup (case-insensitive)
 * @param ipa_out Output buffer for IPA
 * @param max_len Maximum output length
 * @return ETHERVOX_SUCCESS on success, ETHERVOX_ERROR_NOT_FOUND if not found
 */
ethervox_result_t espeak_dict_lookup(
    const espeak_dict_entry_t* entries,
    size_t size,
    const char* word,
    char* ipa_out,
    size_t max_len
);

#ifdef __cplusplus
}
#endif

#endif // ETHERVOX_ESPEAK_DICT_H
